id: I55C89D89
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T00:54:28+00:00'
last_modified: '2022-06-08T06:57:37.078566+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28858
  title: རང་བཞིན་རྫོགས་པ་ཆེན་པོ་མ་བསྒོམ་སངས་རྒྱས་ཀྱི་ཟིན་བྲིས་དཔལ་ལྡན་བླ་མའི་ཞལ་རྒྱུན་ནག་འགྲོས་སུ་བཀོད་པ་ཚིག་དོན་རབ་གསལ་སྐལ་ལྡན་དགྱེས་པའི་མགུལ་རྒྱན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    24B9:
      image_group_id: I4805
      title: ''
      total_pages: 226
      order: 1
      base_file: 24B9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
