id: P006802
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W28858
  title: རང་བཞིན་རྫོགས་པ་ཆེན་པོ་མ་བསྒོམ་སངས་རྒྱས་ཀྱི་ཟིན་བྲིས་དཔལ་ལྡན་བླ་མའི་ཞལ་རྒྱུན་ནག་འགྲོས་སུ་བཀོད་པ་ཚིག་དོན་རབ་གསལ་སྐལ་ལྡན་དགྱེས་པའི་མགུལ་རྒྱན
  author: ''
  volumes:
    549a16cb3811421fac2e4568fdb01bdb:
      image_group_id: I4805
      title: ''
      volume_number: 1
      total_pages: 226
      base_file: v001.txt
