id: P006802
initial_creation_type: ocr
source_metadata:
  id: bdr:W28858
  title: རང་བཞིན་རྫོགས་པ་ཆེན་པོ་མ་བསྒོམ་སངས་རྒྱས་ཀྱི་ཟིན་བྲིས་དཔལ་ལྡན་བླ་མའི་ཞལ་རྒྱུན་ནག་འགྲོས་སུ་བཀོད་པ་ཚིག་དོན་རབ་གསལ་སྐལ་ལྡན་དགྱེས་པའི་མགུལ་རྒྱན
  author: ''
  volumes: {}
